### ISSUE TITLE
Bug in mcmc.py burnin option

### ISSUE THREAD

**Issue by blacy** [ckreisch/ExoplanetSpectra#17]
@HeatherPrince @kengran
When I run mcmc with more than 0 burn in steps I get an error.
It looks like line 33 of mcmc.py needs to be updated to self._sampler.run_mcmc rather than sampler.run_mcmc 

is mcmc.py the latest version of things?

**Comment by kengran** [comment]
Good catch. I have not tested other burnin steps so you are probably right.

**Comment by blacy** [comment]
Cool, I did not change the line of code since I didn't want to mess with your stuff. If you can, try to be writing unit tests and using them as you write each new function. That way this would be caught immediately.


________________________________
