### ISSUE TITLE
Input file consistency

### ISSUE THREAD

**Issue by ckreisch** [ckreisch/ExoplanetSpectra#62]
@blacy please check that recent changes to input_file.txt (and possibly input_file.ini) are incorporated in the input files you are using. We should delete files that are no longer needed

**Comment by blacy** [comment]
moved un-neccesarry ones to non_essential_files

at this point in time, you can use jenkins_test.ini if you want a super fast de-buggin run, heather.ini for a fast run, and example_input.ini for a more realistic size of light curve
